#!/bin/bash

# Written by Hugo Millwood

# This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.


uname=$(uname)
case "$uname" in
    (*Linux*) openCmd='xdg-open';;
    (*Darwin*) openCmd='open';;
    (*) exit 2;;
esac;

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if test $? -eq 128
    then
        echo $BRANCH
    else
        REPO=$(git config --get remote.origin.url | sed 's/\.git//' | sed 's/\git\@github.com:/https\:\/\/www.github.com\//')
        git push --set-upstream origin $BRANCH
        "$openCmd" $REPO/compare/$BRANCH?expand=1
fi

